### ISSUE TITLE
MARIADB_EXTRA_FLAGS prevents initializing

### ISSUE THREAD

**Issue by l0rb** [bitnami/bitnami-docker-laravel#107]
**Description**
I tried to start the container with `MARIADB_EXTRA_FLAGS=--character-set-server=utf8mb4` set but after `mariadb_1  | INFO  ==> Initializing mariadb database...` no more log lines from the mariadb container are printed. It does not exit, it just stops. This results in the app container trying to connect to it but never succeeding creating a stream of `Trying to connect to mariadb at 172.18.0.2. Attempt X.` messages.

**Steps to reproduce the issue:**

1. `curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-laravel/master/docker-compose.yml`
2. Edit the file and add a line `- MARIADB_EXTRA_FLAGS=--character-set-server=utf8mb4` to the environment section of the mariadb service.
3. `docker-compose up`
4. observer the problem as described above

**Describe the results you received:**

The mariadb container doesn't finish initializing. It does not exit with an error either, it seems to just hang forever.

**Describe the results you expected:**

mariadb starting

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:36:00 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 25
 Running: 2
 Paused: 0
 Stopped: 23
Images: 38
Server Version: 18.09.6
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-7-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.676GiB
Name: linx4lorb
ID: BQHA:WH6B:U445:HHDU:DETQ:OQTP:6KHD:SNTT:4YUN:FDXH:4CEP:HOPP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by javsalgar** [comment]
Hi,

I enabled the `BITNAMI_DEBUG=true` env var and saw this error

```
mariadb_1  | 2019-06-26 16:13:55 140292573214592 [ERROR] COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4'
mariadb_1  | 2019-06-26 16:13:55 140292573214592 [ERROR] Aborting
```

It seems to me that an extra parameter is missing in order to make it work. I found this link, which I think could be helpful for the issue https://stackoverflow.com/questions/25852239/collation-utf8-general-ci-is-not-valid-for-character-set-latin1

**Comment by l0rb** [comment]
That fixes this issue! Thank you, was not aware of the possibility to see more debug output.
