### ISSUE TITLE
Command for Deployment mode

### ISSUE THREAD

**Issue by saidmoya12** [bitnami/bitnami-docker-laravel#108]
Please Allow a feature for deployment mode for Laravel

like:
```yml
command: composer install --optimize-autoloader --no-dev
```

Thanks!

**Comment by miguelaeh** [comment]
Hi @saidmoya12 ,
I am not an expert with laravel, but could you try to run that command into the `app-entrypoint.sh` script or even on the Dockerfile?
Probably this could solve your problem.
