### ISSUE TITLE
Xdebug support

### ISSUE THREAD

**Issue by l0rb** [bitnami/bitnami-docker-laravel#109]
Are there any plans to add Xdebug support? With Xdebug installed by default it would be easier to do debugging and get code coverage reports.

**Comment by rafariossaa** [comment]
Hi @l0rb ,
 Thanks for your interest in using Bitnami and for your suggestion. I will share it with our Engineering team so they could take it into account for future improvements.

  Meanwhile,  feel free to send a PR and we'll review and merge it.

Best regards,
