### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by bjorkblom** [bitnami/bitnami-docker-laravel#114]
**Description**

When running docker-compose up I get `The stream or file "/app/storage/logs/laravel.log" could not be opened: failed to open stream: Permission denied`

**Steps to reproduce the issue:**

1. docker-compose up

**Version**

- Output of `docker version`:

```
Docker container on Azure
```

- Output of `docker info`:

```
Docker container on Azure
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
Docker container on Azure

**Comment by juan131** [comment]
Hi @bjorkblom 

Could you share the output of running the command below?

```
$ docker-compose exec myapp ls -la /app/storage/logs
```

By default the permission are:

```
$ docker-compose exec myapp ls -la /app/storage/logs
total 4
drwxr-xr-x 3 root root  96 Sep 13 04:47 .
drwxr-xr-x 5 root root 160 Sep 13 04:47 ..
-rw-r--r-- 1 root root  14 Sep 13 04:47 .gitignore
```

As you can check there's writing permissions for "other" in that directory, so it should be possible to create a file there.

**Comment by bjorkblom** [comment]
This was Azure related. After I mounted a dir it worked as expected. Closing issue

**Comment by debarshibasak** [comment]
i have the same issue on oracle cloud.

**Comment by juan131** [comment]
Hi @debarshibasak 

Some questions:

- What version of the container are you using?
- Are you using Docker Compose to deploy the container? If so, please share the one you're using.
- Are you mounting a volume in the `/app` path? If so, could you run the command I recommended on [this response](https://github.com/bitnami/bitnami-docker-laravel/issues/114#issuecomment-531171350) and share the output?
