### ISSUE TITLE
forcing change of utf8mb4 to utf8 breaks pre-existing indexes

### ISSUE THREAD

**Issue by jeffreyrr** [bitnami/bitnami-docker-laravel#117]
I have an index that can't be created and I narrowed down the issue to the app-entrypoint script forcing utf8 charset

>  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `devices` add index `devices_device_hash_os_version_build_version_index`(`device_hash`, `os_version`, `build_version`))

https://github.com/bitnami/bitnami-docker-laravel/blob/e7b4ae17db051e283175c421785b61621dbf468b/6/debian-9/rootfs/app-entrypoint.sh#L39

**Comment by alemorcuq** [comment]
Hi, @jeffreyrr.

Can you give us some steps in order to reproduce the issue? It would help us understand the issue and figure out a fix. 

Regards,
Alejandro
