### ISSUE TITLE
[ERROR] in kubectl create -f test.yaml

### ISSUE THREAD

**Issue by rtelesc** [bitnami/bitnami-docker-laravel#118]
**Description**

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**
i have attempted to run "kubectl apply -f test.yaml" but  terminal say  error: unable to recognize "test.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"

I'am using the original code from bitnami

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Linux developer-desktop 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

- Output of `docker info`:

```
Containers: 31
 Running: 28
 Paused: 0
 Stopped: 3
Images: 30
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 5.0.0-32-generic
Operating System: Ubuntu 18.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.38GiB
Name: developer-desktop
ID: PN4U:E2PO:TSG4:FBY6:25GD:3NIV:P5ED:GBVR:I6VN:IXSG:QIXW:7YMK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: rtelesc
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```docker-compose version 1.17.1, build unknown
docker-py version: 2.5.1
CPython version: 2.7.15+
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by carrodher** [comment]
There are several deprecations in the API introduced in `K8s 1.16` (see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals) which affect our manifests. The following APIs are no longer served by default:

- All resources under `apps/v1beta1` and `apps/v1beta2` - use `apps/v1` instead
- **daemonsets**, **deployments**, **replicasets** resources under `extensions/v1beta1` - use `apps/v1` instead
- **networkpolicies** resources under `extensions/v1beta1` - use `networking.k8s.io/v1` instead
- **podsecuritypolicies** resources under `extensions/v1beta1` - use `policy/v1beta1` instead

This PR address the changes to be done for Bitnami charts.
What version of kubernetes are you using (`kubectl version`)? In the same way, can you edit the `test.yaml` and implement the following change?
```diff
-apiVersion: extensions/v1beta1
+apiVersion: apps/v1
```

**Comment by rtelesc** [comment]
Hello, thanks for reply.

This kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-17T17:16:09Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rtelesc** [comment]
Hello, after many attempts I managed to solve the problem.

Below are instructions on how to resolve this error.


Using or converting, it creates the necessary files, but you can change file deployments with the following structure.




nginx-deployment.yaml
`apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
     matchLabels:
         io.kompose.service: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
      name: php
    spec:
      containers:
      - image: nginx:1.13
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/www/
          name: php-claim0
        - mountPath: /root/snap/kompose/1/.composer/
          name: php-claim1
      restartPolicy: Always
      volumes:
      - name: php-claim0
        persistentVolumeClaim:
          claimName: php-claim0
      - name: php-claim1
        persistentVolumeClaim:
          claimName: php-claim1
status: {}
`


php-deployment.yaml
`apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: php
  name: php
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
     matchLabels:
         io.kompose.service: php
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
      - env:
        - name: DB_DATABASE
          value: homestead
        - name: DB_HOST
          value: mysql
        - name: DB_PASSWORD
          value: homestead
        - name: DB_USERNAME
          value: homestead
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        image: rtelesc/php:v1
        name: php
        resources: {}
        volumeMounts:
        - mountPath: /var/www/
          name: php-claim0
        - mountPath: /root/snap/kompose/1/.composer/
          name: php-claim1
      restartPolicy: Always
      volumes:
      - name: php-claim0
        persistentVolumeClaim:
          claimName: php-claim0
      - name: php-claim1
        persistentVolumeClaim:
          claimName: php-claim1
status: {}
`

mysql-deployment.yaml
`apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
     matchLabels:
         io.kompose.service: mysql
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: homestead
        - name: MYSQL_PASSWORD
          value: homestead
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        - name: MYSQL_USER
          value: homestead
        image: mysql:5.7
        name: mysql
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: apidicom-mysqldata
      restartPolicy: Always
      volumes:
      - name: apidicom-mysqldata
        persistentVolumeClaim:
          claimName: apidicom-mysqldata
status: {}
`
nginx-service.yaml
`apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
`
