### ISSUE TITLE
Permission Denied when running via podman

### ISSUE THREAD

**Issue by leggettc18** [bitnami/bitnami-docker-laravel#123]
**Description**

When attempting to run the bitnami/laravel container with rootless podman, the container does not seem to have permissions to access the mounted host directory.

```
cp: cannot create regular file '/app/./.editorconfig': Permission denied
cp: cannot create regular file '/app/./.env': Permission denied
cp: cannot create regular file '/app/./.env.example': Permission denied
cp: cannot create regular file '/app/./.gitattributes': Permission denied
cp: cannot create regular file '/app/./.gitignore': Permission denied
cp: cannot create regular file '/app/./.styleci.yml': Permission denied
cp: cannot create regular file '/app/./README.md': Permission denied
cp: cannot create regular file '/app/./artisan': Permission denied
cp: cannot create regular file '/app/./composer.json': Permission denied
cp: cannot create regular file '/app/./composer.lock': Permission denied
cp: cannot create regular file '/app/./package.json': Permission denied
cp: cannot create regular file '/app/./phpunit.xml': Permission denied
cp: cannot create regular file '/app/./server.php': Permission denied
cp: cannot create regular file '/app/./webpack.mix.js': Permission denied
cp: cannot create directory '/app/./bootstrap': Permission denied
cp: cannot create directory '/app/./app': Permission denied
cp: cannot create directory '/app/./config': Permission denied
cp: cannot create directory '/app/./database': Permission denied
cp: cannot create directory '/app/./public': Permission denied
cp: cannot create directory '/app/./resources': Permission denied
cp: cannot create directory '/app/./routes': Permission denied
cp: cannot create directory '/app/./storage': Permission denied
cp: cannot create directory '/app/./tests': Permission denied
cp: cannot create directory '/app/./vendor': Permission denied
cp: preserving times for '/app/.'
```
This happens as soon as the container is started and then the container stops. Host is running Fedora 31, fails whether SELinux is enabled or not, whether volume is mounted with :Z or :z. Haven't tried starting the container as root but would rather not as being rootless is half the point of me using podman instead of docker.

The podman run command I am using...

```
podman run -d \
    --name cabinet-laravel \
    -v $PWD/src:/app:z \
    --pod cabinet \
    bitnami/laravel
```

I create the pod in an earlier step, cabinet is just the name of the app I am trying to write.

**Steps to reproduce the issue:**

1. issue the `podman run <options> bitnami/laravel` command.
2. Run `podman ps` and see that the laravel container is not running.
3. Check `podman logs <container-name>` to see the above logs.

**Describe the results you received:**

Container dies, no laravel app is initialized

**Describe the results you expected:**

Container is started, laravel app is initialized

**Additional information you deem important (e.g. issue happens only occasionally):**

Am running podman instead of docker, supposed to be equivalent in terms of the containers it can run. Don't have this issue with other containers, in fact I have another php-fpm container for another non-laravel project I am working on which works perfectly fine with a similar `podman run` command (really the only thing different is the exact path and the names).

**Version**

- Output of `docker version`:

```
Version:            1.7.0
RemoteAPI Version:  1
Go Version:         go1.13.5
OS/Arch:            linux/amd64

```

- Output of `docker info`:

```
host:
  BuildahVersion: 1.12.0
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.9-2.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.9, commit: 7d46f3e7711aa3578488284ae2f98b447658f086'
  Distribution:
    distribution: fedora
    version: "31"
  IDMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  MemFree: 2231808000
  MemTotal: 16707850240
  OCIRuntime:
    name: crun
    package: crun-0.10.6-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 8459907072
  SwapTotal: 8459907072
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: battlestation
  kernel: 5.4.13-201.fc31.x86_64
  os: linux
  rootless: true
  slirp4netns:
    Executable: /usr/bin/slirp4netns
    Package: slirp4netns-0.4.0-20.1.dev.gitbbd6f25.fc31.x86_64
    Version: |-
      slirp4netns version 0.4.0-beta.3+dev
      commit: bbd6f25c70d5db2a1cd3bfb0416a8db99a75ed7e
  uptime: 157h 13m 5.03s (Approximately 6.54 days)
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - registry.centos.org
  - quay.io
store:
  ConfigFile: /home/chris/.config/containers/storage.conf
  ContainerStore:
    number: 4
  GraphDriverName: overlay
  GraphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-0.7.5-2.fc31.x86_64
      Version: |-
        fusermount3 version: 3.6.2
        fuse-overlayfs: version 0.7.5
        FUSE library version 3.6.2
        using FUSE kernel interface version 7.29
  GraphRoot: /home/chris/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  ImageStore:
    number: 4
  RunRoot: /run/user/1000/containers
  VolumePath: /home/chris/.local/share/containers/storage/volumes
```

- Output of `docker-compose version` (if applicable):

```n/a
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Fedora 31 Workstation using Podman

**Comment by miguelaeh** [comment]
Hi @leggettc18 ,
Could you share the permissions of the local directory you are mounting? It is probably the user running inside the `podman` pod does not have permissions on that directory. Have in mind the permissions on the mounted directory will be the same as the permissions on your local machine.

**Comment by leggettc18** [comment]
I'm not in front of the computer right this minute, but it's a folder I made directly before running the container so it should just have my user's permissions on it. I'll get the exact permissions as soon as I can.

**Comment by leggettc18** [comment]
The computer I was on was having internet troubles, so I couldn't copy paste, but here are the permissions on the folder I am trying to mount to the container, received from `ls -la`

```
drwxr-xr-x. 2 chris chris 4096 Feb 2 20:07 src/
```

And that folder is empty.

**Comment by leggettc18** [comment]
So for some reason after I rebooted and installed some updates and it started working? Weird, as I checked the updates and didn't see anything related to containers there. I did also attempt to `chmod -R a+rwx` on the directory as a last resort, but it didn't work until after the reboot, so I don't think that did it... Regardless, I'm happy its working now and thank you for your time. If you need anything else from me please feel free to let me know.
