### ISSUE TITLE
[FEATURE REQUEST] Upgrade to php 7.4

### ISSUE THREAD

**Issue by iSWORD** [bitnami/bitnami-docker-laravel#126]
I've recently started using this docker image and found it very helpful for CI.

I was just wondering, what's your timeline for upgrading to php 7.4?

Let me know if there's anything I can help with.

**Comment by andresbono** [comment]
Hi @iSWORD, thanks for opening this issue.

In general, we move all our components to a newer PHP version at the same time to ease maintainability. There are exceptions when the applications requirements recommends a specific version, but for the case of Laravel, we are safe to use PHP 7.3: https://laravel.com/docs/7.x#server-requirements. We will migrate all the PHP applications to use the 7.4 runtime, but I can't tell you a specific date at this moment.

Why do you think it would be better to use PHP 7.4? If you want, you can create your custom image based on our Dockerfile. Let us know if you are interested on this.

**Comment by iSWORD** [comment]
Hi @andresbono 

Thank you for your response. I had some packages in my project that dropped support for 7.3, but I guess I could just use older versions of those packages until this image gets updated.

Thank you,

**Comment by andresbono** [comment]
Thanks, @iSWORD.
