### ISSUE TITLE
app-entrypoint forces utf8 by updating a working directory configuration

### ISSUE THREAD

**Issue by Illizian** [bitnami/bitnami-docker-laravel#129]
This is arguably a question, more than it is a bug (...yet) but I was just wondering what the thinking behind this line of the [entrypoint](https://github.com/bitnami/bitnami-docker-laravel/blob/master/7/debian-10/rootfs/app-entrypoint.sh#L71) is:

```
replace_in_file "/app/config/database.php" "utf8mb4" "utf8"
```

There are some things that make me a little uncomfortable about this line. One is, it seems advisable to not touch my working directory, and, two it's opinionated?

**Steps to reproduce the issue:**

1. Extend the `bitnami/laravel` image or use in `docker-compose.yml`
2. Launch image

**Describe the results you received:**

`/app/config/database.php` has been updated from utf8mb4 to utf8

**Describe the results you expected:**

The image to launch and allow me to use utf8mb4 against my database of choice, in this instance, MariaDB 10.4.

**Additional information you deem important (e.g. issue happens only occasionally):**

As I say, this is more of a question than a bug and I fully accept there's a legitimate reason for this and would like to learn what that is. I would be happy to close without remediation (This is the motivation I've needed to make my own image haha)

**Comment by rafariossaa** [comment]
Hi,
  Thanks for noticing this.
  Yes, you are right, this should not be being changed.
  I am opening a task to change this.

**Comment by Illizian** [comment]
@rafariossaa Oh, that's great to hear - I wasn't sure whether to raise the issue or not as it felt like feedback more than constructive :smile:

I'm happy to make the change :+1: (PR to follow)

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay. 
  We are working to make a new release. I will come back a soon as it is out.

**Comment by rafariossaa** [comment]
Hi, 
 The new image was released.
  Could you give it a try ? , have into account that the docker compose file was also updated to include mariadb 10.2 .

**Comment by Illizian** [comment]
Thanks @rafariossaa!

:+1: I didn't realise the image included MariaDB, I usually use a separate container and to be fair usually use 10.4

I'll give it a quick test and report back when I get a chance

**Comment by rafariossaa** [comment]
Hi,
  The laravel image doesn't include mariadb. Maybe I don't expressed myself very clearly.
  What uses the mariadb image is the docker-compose file. I thought you were using that docker-compose file.

**Comment by Illizian** [comment]
Ah! Sorry, yes I am using docker-compose but not the version contained in
this repo.

Thanks

**Comment by rafariossaa** [comment]
Hi,
  Ok, thanks for the clarification.
