### ISSUE TITLE
how to install php modules?

### ISSUE THREAD

**Issue by sshnuke3** [bitnami/bitnami-docker-laravel#131]
for example, i want to install php-mongodb module
if i input apt-get install php-mongodb, it will install another php for me and i could not use the module when i start the container
if i input pecl install mongodb, it will report no autoconf and gcc, etc found
so how could i install other php modules as i wish?

**Comment by carrodher** [comment]
Hi, I think this issue was already discussed here (https://github.com/bitnami/bitnami-docker-laravel/issues/76), as the module is not included in the container, it needs to be compiled properly. Can you follow the steps described in this issue (although in the issue the module installed is a different one?

**Comment by sshnuke3** [comment]
my dockerfile is like this
FROM docker.io/bitnami/laravel:7-debian-10
RUN install_packages \
    git autoconf build-essential pkg-config \
    libmemcached-dev libmemcached11 libmemcachedutil2 libhashkit2
RUN sudo pecl install mongodb

when i build it reports E: List directory /var/lib/apt/lists/partial is missing. - Acquire (2: No such file or directory)

**Comment by sshnuke3** [comment]
i changed my dockerfile to
FROM docker.io/bitnami/laravel:7-debian-10
COPY sources.list /etc/apt/sources.list
RUN sudo install_packages \
    git autoconf build-essential pkg-config \
    libmemcached-dev libmemcached11 libmemcachedutil2 libhashkit2
RUN sudo pecl install mongodb
RUN sudo echo extention=mongodb.so >> /opt/bitnami/php/etc/php.ini

but when i build it reports
/bin/sh: 1: cannot create /opt/bitnami/php/etc/php.ini: Permission denied
The command '/bin/sh -c sudo echo extention=mongodb.so >> /opt/bitnami/php/etc/php.ini' returned a non-zero code: 2

so how can i add other extensions to php using this image?

**Comment by carrodher** [comment]
I was able to build the following Dockerfile:
```Dockerfile
 FROM docker.io/bitnami/laravel:7-debian-10
 USER root
 RUN sudo install_packages git autoconf build-essential pkg-config libmemcached-dev libmemcached11 libmemcachedutil2 libhashkit2
 RUN sudo pecl install mongodb
 RUN sudo echo extention=mongodb.so >> /opt/bitnami/php/etc/php.ini
```
It is the same you posted but with a couple of changes:
1) It is using root as user
2) It is not using the `COPY` as I don't have a `source.list` in my local

Apart from that, it's the same Dockerfile, I was able to build it by running `docker build`

**Comment by sshnuke3** [comment]
> ```dockerfile
> USER root
> ```

i just added USER root to my dockerfile and it works!
thanks a lot~
