### ISSUE TITLE
failed to create laravel project

### ISSUE THREAD

**Issue by sshnuke3** [bitnami/bitnami-docker-laravel#133]
```
[root@VM-4-17-centos myapp]# docker-compose logs myapp
Attaching to myapp_myapp_1
myapp_1    | 
myapp_1    | Welcome to the Bitnami laravel container
myapp_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-laravel
myapp_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-laravel/issues
myapp_1    | 
myapp_1    | Creating laravel application
myapp_1    | cp: cannot create regular file '/app/./.editorconfig': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.env': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.env.example': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.gitattributes': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.gitignore': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.styleci.yml': Permission denied
myapp_1    | cp: cannot create regular file '/app/./README.md': Permission denied
myapp_1    | cp: cannot create directory '/app/./app': Permission denied
myapp_1    | cp: cannot create regular file '/app/./artisan': Permission denied
myapp_1    | cp: cannot create directory '/app/./bootstrap': Permission denied
myapp_1    | cp: cannot create regular file '/app/./composer.json': Permission denied
myapp_1    | cp: cannot create regular file '/app/./composer.lock': Permission denied
myapp_1    | cp: cannot create directory '/app/./config': Permission denied
myapp_1    | cp: cannot create directory '/app/./database': Permission denied
myapp_1    | cp: cannot create regular file '/app/./package.json': Permission denied
myapp_1    | cp: cannot create regular file '/app/./phpunit.xml': Permission denied
myapp_1    | cp: cannot create directory '/app/./public': Permission denied
myapp_1    | cp: cannot create directory '/app/./resources': Permission denied
myapp_1    | cp: cannot create directory '/app/./routes': Permission denied
myapp_1    | cp: cannot create regular file '/app/./server.php': Permission denied
myapp_1    | cp: cannot create directory '/app/./storage': Permission denied
myapp_1    | cp: cannot create directory '/app/./tests': Permission denied
myapp_1    | cp: cannot create directory '/app/./vendor': Permission denied
myapp_1    | cp: cannot create regular file '/app/./webpack.mix.js': Permission denied
myapp_1    | cp: preserving times for '/app/.': Operation not permitted
```

**Comment by carrodher** [comment]
When creating a new issue, a template like the below one appears where you can put some information that is useful for us in order to debug/reproduce the issue, please, can you fill that form?

There are different Laravel branches, that is why it's something important to know. In the same way, what are the steps to reproduce the issue? Did you perform any customization?

It's also important to know if you are using a windows machine, in that case a small change is required in the docker-compose:
```yaml
...
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
```

Also, what are the permissions of your current dir? Please note that the current dir is going to be mounted in the container `/app` dir.

⬇️ See below an example template


**Description**



**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Describe the results you received:**



**Describe the results you expected:**



**Additional information you deem important (e.g. issue happens only occasionally):**



**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by sshnuke3** [comment]
Description
Creating laravel application failed


Steps to reproduce the issue:

[First Step]
mkdir ~/myapp && cd ~/myapp
[Second Step]
curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-laravel/master/docker-compose.yml
[and so on...]
docker-compose up
Describe the results you received:
myapp_1    | Creating laravel application
myapp_1    | cp: cannot create regular file '/app/./.editorconfig': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.env': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.env.example': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.gitattributes': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.gitignore': Permission denied
myapp_1    | cp: cannot create regular file '/app/./.styleci.yml': Permission denied
myapp_1    | cp: cannot create regular file '/app/./README.md': Permission denied
myapp_1    | cp: cannot create directory '/app/./app': Permission denied
myapp_1    | cp: cannot create regular file '/app/./artisan': Permission denied
myapp_1    | cp: cannot create directory '/app/./bootstrap': Permission denied
myapp_1    | cp: cannot create regular file '/app/./composer.json': Permission denied
myapp_1    | cp: cannot create regular file '/app/./composer.lock': Permission denied
myapp_1    | cp: cannot create directory '/app/./config': Permission denied
myapp_1    | cp: cannot create directory '/app/./database': Permission denied
myapp_1    | cp: cannot create regular file '/app/./package.json': Permission denied
myapp_1    | cp: cannot create regular file '/app/./phpunit.xml': Permission denied
myapp_1    | cp: cannot create directory '/app/./public': Permission denied
myapp_1    | cp: cannot create directory '/app/./resources': Permission denied
myapp_1    | cp: cannot create directory '/app/./routes': Permission denied
myapp_1    | cp: cannot create regular file '/app/./server.php': Permission denied
myapp_1    | cp: cannot create directory '/app/./storage': Permission denied
myapp_1    | cp: cannot create directory '/app/./tests': Permission denied
myapp_1    | cp: cannot create directory '/app/./vendor': Permission denied
myapp_1    | cp: cannot create regular file '/app/./webpack.mix.js': Permission denied
myapp_1    | cp: preserving times for '/app/.': Operation not permitted
myapp_myapp_1 exited with code 1


Describe the results you expected:
i hope it works

Additional information you deem important (e.g. issue happens only occasionally):

Version

Output of docker version:
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Wed Oct 14 19:43:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Wed Oct 14 16:41:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu2
  GitCommit:
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:
 docker-init:
  Version:          0.18.0
  GitCommit:


Output of docker info:
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 2
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version:
 runc version:
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-42-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 1.941GiB
 Name: VM-0-5-ubuntu
 ID: Z7DN:UELV:IORD:AMD7:RKDK:SDJV:PRYP:UE2Z:K364:PQGJ:5ACY:ISMP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support


Output of docker-compose version (if applicable):
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.5
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020


Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):
tencentyun ( cloud.tencent.com )

**Comment by miguelaeh** [comment]
Hi @sshnuke3 ,
The docker-compose is mounting the local directory as a volume. Please change the permissions of the local directory before the `docker-compose up` to `bitnami`.
```
sudo chown -R bitnami .
docker-compose up
```
