### ISSUE TITLE
Php Version is Outdated

### ISSUE THREAD

**Issue by turkmenkaan** [bitnami/bitnami-docker-laravel#135]
In both laravel 7 and laravel 8 images, the required php version is +7.4.4 but the included one is 7.3.25. Therefore, myapp service fails to build.

This is the error I get after `docker-composer up`

```
myapp_1    | Loading composer repositories with package information
myapp_1    | Installing dependencies (including require-dev) from lock file
myapp_1    | Your requirements could not be resolved to an installable set of packages.
myapp_1    |
myapp_1    |   Problem 1
myapp_1    |     - This package requires php ^7.4.4 but your PHP version (7.3.25) does not satisfy that requirement.
myapp_1    |
```

**Comment by turkmenkaan** [comment]
If you can verify this issue, I can open a PR on the relevant Dockerfile.

**Comment by beltran-rubo** [comment]
Thanks for reporting it. It seems Laravel requires PHP >= 7.2.5 based on https://laravel.com/docs/7.x/installation and that is a requirement for one of the dependencies in your application. In any case we are working on updating it to use the latest PHP 7.4.x for Laravel and it should be released today.

**Comment by beltran-rubo** [comment]
Latest versions of Laravel container image uses PHP 7.4.13:  7.30.1-debian-10-r50 and 8.5.5-debian-10-r11
