### ISSUE TITLE
Start Laravel container without database

### ISSUE THREAD

**Issue by fdbatista** [bitnami/bitnami-docker-laravel#137]
Hello.
This is not exactly a Feature Request, but I would like to know how can I start the Laravel container without it constantly trying to connect to MySQL.

I only need the application running, and having an useless MySQL container running makes no sense to me.

Thanks.

**Comment by juan131** [comment]
Hi @fdbatista 

The container's **entrypoint** waits for a database by default, see:

- https://github.com/bitnami/bitnami-docker-laravel/blob/master/8/debian-10/rootfs/app-entrypoint.sh#L47
- https://github.com/bitnami/bitnami-docker-laravel/blob/master/8/debian-10/rootfs/app-entrypoint.sh#L91

However, this only happens when the command used to launch the container contains `php artisan serve`, see:

- https://github.com/bitnami/bitnami-docker-laravel/blob/master/8/debian-10/rootfs/app-entrypoint.sh#L76

This is the default behaviour (see https://github.com/bitnami/bitnami-docker-laravel/blob/master/8/debian-10/Dockerfile#L33), but it can be easily modified by using a different command to launch the container. For instance:

```
$ docker run --rm -it bitnami/laravel:8-debian-10 bash
```

**Comment by fdbatista** [comment]
Hi, @juan131. Thanks for your response.

I want to run a single Docker container with the Laravel app in detached mode, so the `docker run --rm -it bitnami/laravel:8-debian-10 bash` command does not work for me. And the `-d` parameter makes the container exit automatically.

Maybe this is not the right place to ask, but what should I do? Creating my own image by building a custom Dockerfile taking https://github.com/bitnami/bitnami-docker-laravel/blob/master/8/debian-10/Dockerfile#L33 as starting point and modifying its ENTRYPOINT or the CMD sentence?

**Comment by juan131** [comment]
Hi @fdbatista 

Building your own container is a possibility.
Another possibility will be using some command that waits forever, For instance:

```console
$ docker run --rm -d --name laravel bitnami/laravel:8-debian-10 sleep infinity
```

Then, since your container is running, you can exec into it and run any desired command:?

```console
$ docker exec -it laravel bash
...
```

**Comment by fdbatista** [comment]
Hi @juan131 .
Actually I want the web server up and running, but without having to start a Docker container.
I started to play with your suggestions and ended up with this command:

```bash
docker run -v $PWD:/app -d --name laravel_test --network=host --rm bitnami/laravel:8.5.6 sleep infinity && docker exec -d xn_test php artisan serve --port=8080
```

I don't know if it is the best way, but I haven't been able to find another one.
Thanx a lot!

**Comment by juan131** [comment]
Hi @fdbatista 

I think you can get a similar result without doing two concatenated commands. Try this (overwriting the entrypoint):

```console
$ docker run \
  -v $PWD:/app \
  --rm -d --name laravel_test \
  --network=host \
  --entrypoint "php" \
  bitnami/laravel:8.5.6 \
  artisan serve --port=8080
```

**Comment by fdbatista** [comment]
> Hi @fdbatista
> 
> I think you can get a similar result without doing two concatenated commands. Try this (overwriting the entrypoint):
> 
> ```
> $ docker run \
>   -v $PWD:/app \
>   --rm -d --name laravel_test \
>   --network=host \
>   --entrypoint "php" \
>   bitnami/laravel:8.5.6 \
>   artisan serve --port=8080
> ```

Great!
I didn't  know how to override the entrypoint, this example does exactly what I want.
Thank you very much for your help!

Closing the issue now 👍

**Comment by juan131** [comment]
You're welcome @fdbatista ! Don't hesitate to let us know if you require further help.
