### ISSUE TITLE
Questions about Docker Image Vulnerability Reporting

### ISSUE THREAD

**Issue by ssst0n3** [bitnami/bitnami-docker-laravel#138]
Seems I have found a vulnerability in docker image bitnami/laravel. 

But I do not find where to report it. Could you please tell me how to report this vulnerability? 
Should I send the details to a specific email address? Or just file an issue on github(https://github.com/bitnami/bitnami-docker-laravel)? Or maybe I should report to mitre(cve) directly?

(Make the details public maby not a responsible disclosure)

**Comment by beltran-rubo** [comment]
Hi @ssst0n3, could you please email the details to security (at) bitnami [dot] com? We will review those details and get back to you as soon as possible, thanks.

**Comment by ssst0n3** [comment]
thank you, i've already sent an email to security@bitnima.com and security@vmware.com(follow the redirect by security@bitnami.com).
