### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by runthis** [bitnami/bitnami-docker-laravel#147]
https://github.com/bitnami/bitnami-docker-laravel/blob/c7e036f98408080f5aff2d6c08d5078f2e1b0d13/8/debian-10/Dockerfile#L12

Can we get another option for Laravel 8 with PHP 8? Currently using `docker.io/bitnami/laravel:8`

**Comment by migruiz4** [comment]
Hi @runthis,

I'm sorry but we currently only release Laravel 8 with PHP 7.4. To use it with PHP 8 you would need to build a custom image using Laravel's [Dockerfile](https://github.com/bitnami/bitnami-docker-laravel/blob/master/8/debian-10/Dockerfile), but replacing:
```diff
- RUN bitnami-pkg unpack php-7.4.22-1 --checksum 3ef2eb24c358a84f03bf1eee1747a1379bac7ab2c54601abae4423a72ed6f843
+ RUN bitnami-pkg unpack php-8.0.9-1 --checksum e75bd6d2a11128706243bdb1fecda7e9200372ff6b9f579d4fe6e7022b634b0b
```

**Comment by runthis** [comment]
@migruiz4 Thank you. Keep in mind PHP 7.4 active support ends in 3 months and security updates end in 1 year and 3 months. It might be worth getting ahead with a PHP 8 version :-)
