### ISSUE TITLE
Make upgrading Lavavel dependencies optional

### ISSUE THREAD

**Issue by boosh** [bitnami/bitnami-docker-laravel#148]
I'm building this container in a pipeline before deploying. I'm baking in all the dependencies. However, after the container goes live it won't serve traffic for several minutes because it runs `composer update`. Please add a way of making this optional.

**Steps to reproduce the issue:**

1. Run container. It will run `composer update` if dependencies are already present.

**Describe the results you received:**

**Describe the results you expected:**

It should be possible to skip running `composer update`

**Additional information you deem important (e.g. issue happens only occasionally):**

Latest

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi, [`bitnami/laravel:8.6.1-debian-10-r7`](https://github.com/bitnami/bitnami-docker-laravel/commit/1aac3dd67e1943c85553093e29a768d08340c238) was just released.

**Comment by boosh** [comment]
That's great, thanks
