### ISSUE TITLE
start from Mac Docker Desktop takes long time.

### ISSUE THREAD

**Issue by 1ocate** [bitnami/bitnami-docker-laravel#156]
**Description**

Hi thank for everything.

When I using from Mac with docker-desktop. 
It is start up take longtime.

<img width="851" alt="Screen Shot 2022-01-24 at 3 47 14 PM" src="https://user-images.githubusercontent.com/29521447/150753893-38ca4d9d-5c24-47d6-94e8-96aadc53db25.png">

can see in screenshot in yellow box.

My docker version is

<img width="494" alt="Screen Shot 2022-01-24 at 4 16 15 PM" src="https://user-images.githubusercontent.com/29521447/150754667-6a19a79c-e80a-49a4-9c8b-ac0cadbe3b2a.png">

**Comment by javsalgar** [comment]
Hi,

Thanks for the PR! The team will take a look
