### ISSUE TITLE
When creating a new project in a different folder, the project is not created

### ISSUE THREAD

**Issue by daprela** [bitnami/bitnami-docker-laravel#162]
### Name and Version

bitnami/laravel:9

### What steps will reproduce the bug?

1. Docker desktop for Windows 10
2. Laravel standard configuration with standard docker-compose file as provided
3. run docker-compose up
4. The bitnami container cannot start because there aren't any Laravel files

### What is the expected behavior?

When I create a new project folder I expect to have new containers and a new Laravel project in the my-app folder

### What do you see instead?

The containers are created but during the startup of the laravel containers I get the following messages:

laravel 11:02:07.41 INFO  ==> An existing project was detected, skipping project creation 
laravel 11:02:07.42 INFO  ==> ** Laravel setup finished! **                               
                                                                                          
laravel 11:02:07.42 INFO  ==> ** Starting Laravel project **                              
Could not open input file: artisan                                                        
exited with code 1                                                                           

### Additional information

I tried to create different folders, adding and not adding manually the my-project folder but nothing happens, the Laravel project is never created

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-laravel#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
