### ISSUE TITLE
Add Redis , Mysql 

### ISSUE THREAD

**Issue by abbasfisal** [bitnami/bitnami-docker-laravel#164]
### Name and Version

Redis , Mysql

### What is the problem this feature will solve?

the problem is most project needs mysql and redis and your docker-compose not solving this

### What is the feature you are proposing to solve the problem?

i suggest that add the mysql and redis to the docker-composer , bcz most used db and cache is mysql, redis

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-laravel#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
