### ISSUE TITLE
laravel:latest should point to laravel's latest distribution

### ISSUE THREAD

**Issue by johngerome** [bitnami/bitnami-docker-laravel#25]
For the **latest** tag, Instead of pointing to `create-project "laravel/laravel=5.2.31"` why not use `create-project --prefer-dist laravel/laravel` ? then make a tag for specific laravel version.

**Comment by juan131** [comment]
@johngerome whenever a new version is released that value is updated to the latest version. 

The tag "latest" (in the Docker Image) always points to a tag with latest version that has been **tested.**

If you change it to use `create-project --prefer-dist laravel/laravel`, you can't guarantee that the Laravel version has already been tested by Bitnami.
