### ISSUE TITLE
Codenvy Provisioning Error

### ISSUE THREAD

**Issue by HalfEatenPie** [bitnami/bitnami-docker-laravel#30]
Error within the docker agent is shown when used within Codenvy.  This issue is limited to this image as far as I can tell.

**Reproduction Steps:**

1. Create new workspace with Bitnami Laravel
2. Deploy
3. Error on "ssh-keygen: generating new host keys: RSA1"

**Error Code:**
Could not start workspace test-wksp-1c7o. Reason: Start of environment default failed. Error: Restoring of workspace workspaceylt78i70ue5brgvx filesystem terminated on <FQDN> node. Process failed. Exit code 12

**Environment Details:**
Ubuntu 16.04 64-bit, Codenvy installed using Docker.  
Codenvy version 5.0.0-M7

Don't think this will help but might as well put it...
**Container Console Output:** https://paste.ee/p/U1NrI#hVuezUeJS2sT4BSAGQXJl7KCCeQZ0pID

Any thoughts? I'm not sure what Exit Code 12 would be.

**Comment by prydonius** [comment]
Just tried on the hosted codenvy version (also 5.0.0-M7) and I didn't run into the same issue you did, but I am getting an empty project directory and no laravel app.

Everything works fine using the 'Developer Workspace' link the the README, however.

cc @amrecio any ideas?

**Comment by amrecio** [comment]
It seems @HalfEatenPie is running Codenvy version 5.0.0-M7. That version was tagged on [10 November](https://github.com/eclipse/che/commit/315056731e6a8345c176ca8ac48750188415af4e). However, the PR that [updated](https://github.com/eclipse/che/pull/3051) the Bitnami stacks for the new version of Che/Codenvy was merged on 14 November and it was added to milestone 5.0.0-M8.

It's very likely this is happening on an old version of the Laravel container, which wasn't tested with version 5.0.0 of Che.

**Comment by sameersbn** [comment]
@HalfEatenPie do you have any updates for us?

**Comment by HalfEatenPie** [comment]
@sameersbn Hello!  Terribly sorry about getting to you so late.  

Yes I've upgraded to Codenvy Version 5.0.0-M8 and the same problem still persists.  "tail" of the log shows:

```
[STDOUT] Creating SSH2 ECDSA key; this may take some time ...
[STDOUT] 256 a5:a4:35:76:6b:a7:b2:0f:2c:4b:04:28:bd:2f:59:07 /etc/ssh/ssh_host_ecdsa_key.pub (ECDSA)
[STDOUT] Creating SSH2 ED25519 key; this may take some time ...
[STDOUT] 256 d6:ad:73:9d:6f:4c:95:83:cf:54:15:52:94:c2:2a:e3 /etc/ssh/ssh_host_ed25519_key.pub (ED25519)
[STDOUT] /usr/sbin/invoke-rc.d: 1: /usr/sbin/invoke-rc.d: /sbin/runlevel: not found
[STDOUT] invoke-rc.d: policy-rc.d denied execution of start.
[STDOUT] Setting up tcpd (7.6.q-25) ...
[STDOUT] Setting up xauth (1:1.0.9-1) ...
[STDOUT] Processing triggers for libc-bin (2.19-18+deb8u6) ...
[STDOUT] ssh-keygen: generating new host keys: RSA1

```

**Comment by amrecio** [comment]
Hello @HalfEatenPie,

The error message about `ssh-keygen` is harmless but the workspace should start nonetheless. I've tried to launch a Bitnami Laravel workspace on the hosted Codenvy version at codenvy.io and it worked as it should. The current version there is 5.1.2.

Could you give it another try using the latest version?

Thanks.
