### ISSUE TITLE
Target not found error during build with Dockerfile

### ISSUE THREAD

**Issue by TheRangor** [bitnami/bitnami-docker-laravel#42]
I get this error during docker-compose up when im building with the dockerfile:

```
Building myapp
Step 1/18 : FROM gcr.io/stacksmith-images/minideb:jessie
ERROR: Service 'myapp' failed to build: target is unknown
```

**Comment by prydonius** [comment]
Hey @TheRangor, unfortunately this is an issue in Docker 1.13.0 (https://github.com/docker/docker/issues/30083), and is fixed in 1.13.1. You will either need to upgrade or downgrade to fix this.
