### ISSUE TITLE
Having issues with opcache validation frequence. / Views updated only a minute later.

### ISSUE THREAD

**Issue by 4goodapp** [bitnami/bitnami-docker-laravel#57]
Hello,
When I edit a Laravel view file, change are reflected only 60 seconds later in the browser, 
I made some searches and it seems like that `opcache.revalidate_freq` is set to 60 in the `/opt/bitnami/php/conf/php.ini` file. 
change it to 0 like this `opcache.revalidate_freq = 0` solve the problem.
Is this a bug? Or is this how it's supposed to work?

_**bitnami/laravel     5.4.16-r0**_

**Comment by andresbono** [comment]
Hello @4goodapp,

Thanks for reporting this. We will evaluate the change you propose and we will let you know if we include it in future revisions of the `php` module.

Thanks again,
Andrés.

**Comment by BrianAndersen78** [comment]
Yeah... It's a great build for Laravel, but this update delay i a pain in the a.... :D 

BTW: Thanks for another great bitnami container!

**Comment by andresbono** [comment]
Hi, this issue has been open for a while now. We have not included this change in the container yet.

What you can do for now is applying the following change in the Dockerfile and rebuild the container:

```diff
 RUN npm install -g gulp

+RUN echo "opcache.revalidate_freq = 0" >> /opt/bitnami/php/etc/php.ini
+
 USER bitnami
```

Now, if you execute it, you will have the `opcache.revalidate_freq` parameter set to `0` in the `/opt/bitnami/php/etc/php.ini` file.

Hope this works for you. And thanks for the feedback!
-Andrés B.

**Comment by myokoko-megliofuturo** [comment]
Similar behavior happening for the API routes. Route prefix changes are not immediately reflected. Since the container is installed by the instructions of the **Getting Started** section, the Dockerfile is not included. Any suggestion for this?

**Comment by andresbono** [comment]
Hi @myokoko-megliofuturo,

Instead of downloading the docker-compose file only, you can clone the whole repository and then modify and rebuild the Docker image.

```
git clone https://github.com/bitnami/bitnami-docker-laravel.git
```

**Comment by E-Bismuth** [comment]
other way : first line of server.php : opcache_reset();

**Comment by Juljan** [comment]
> Similar behavior happening for the API routes. Route prefix changes are not immediately reflected. Since the container is installed by the instructions of the **Getting Started** section, the Dockerfile is not included. Any suggestion for this?

In case it can help, I solved it creating a Dockerfile whose content was : 
```
FROM bitnami/laravel:8

USER root
#Solves the cache issue
RUN echo "opcache.revalidate_freq = 0" >> /opt/bitnami/php/etc/php.ini
#Solves the composer memory issue
RUN echo "memory_limit = -1" >> /opt/bitnami/php/etc/php.ini

USER bitnami
ENTRYPOINT [ "/app-entrypoint.sh" ]
CMD [ "php", "artisan", "serve", "--host=0.0.0.0", "--port=3000" ]
```

Then, in you main docker-compose.yml file, a reference to this Dockerfile: 


```
  laravel:
    tty: true
    build:
      context: ./backend/docker/laravel
#   container_name: laravel
    labels:
      ...
```

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-laravel#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
