### ISSUE TITLE
how to add or enable php extensions

### ISSUE THREAD

**Issue by coolflame87** [bitnami/bitnami-docker-laravel#76]
I am using bitnami-docker-laravel container. How can i add or enable php extensions on it.

**Comment by juan131** [comment]
Hi, you need to edit the file `/opt/bitnami/php/etc/php.ini` and ensure your extensions is included in the format:

```
extension=YOUR_EXTENSION.so
```

You can later run `/opt/bintami/php/bin/php -m` to check whether it's has been enabled or not.

**Comment by coolflame87** [comment]
I want to add xdebug. unable to find it in `/opt/bitnami/php/etc/php.ini `.
I try to install it via pecl
```
downloading xdebug-2.5.5.tgz ...
Starting to download xdebug-2.5.5.tgz (279,491 bytes)
................................done: 279,491 bytes
76 source files, building
running: phpize
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

ERROR: `phpize' failed
```
Is their any  way I can add php extensions in a container

**Comment by coolflame87** [comment]
any plan to add xdebug and other useful extensions in docker image.?

**Comment by juan131** [comment]
@tompizmor @jotadrilo what do you think about including this extension on the PHP Nami module?

**Comment by rquadling** [comment]
Hi. I'm NOT an expert here, but the solution we have is ...

```yml
FROM bitnami/php-fpm:7.2 as builder
RUN install_packages \
    git autoconf build-essential pkg-config \
    libmemcached-dev libmemcached11 libmemcachedutil2 libhashkit2
WORKDIR /app

# Build and install xDebug
RUN \
    wget -v --show-progress https://xdebug.org/files/xdebug-2.6.0.tgz -O xdebug.tgz && \
    tar xzf xdebug.tgz && \
    rm -f xdebug.tgz && \
    cd xdebug-*/ && \
    phpize && \
    ./configure --with-php-config=/opt/bitnami/php/bin/php-config && \
    make && \
    TEST_PHP_ARGS='-n' make test && \
    make install && \
    cd .. && \
    rm -Rf xdebug-*/

# Install additional extensions
RUN \
    pecl install \
        igbinary \
        memcached \
        msgpack \
        pdo_dblib \
        redis \
        timecop \
        timezonedb

FROM bitnami/php-fpm:7.2-prod

# Copy dependant shared libraries
COPY --from=builder \
    /usr/lib/x86_64-linux-gnu/libmemcached*.so.*.*.* \
    /usr/lib/x86_64-linux-gnu/libsybdb.so.*.*.* \
    /usr/lib/x86_64-linux-gnu/

# Make symlinks for shared dependant libraries
RUN \
    ln -sf /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0.0 /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0 && \
    ln -sf /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0.0 /usr/lib/x86_64-linux-gnu/libmemcached.so.11 && \
    ln -sf /usr/lib/x86_64-linux-gnu/libmemcached.so.11.0.0 /usr/lib/x86_64-linux-gnu/libmemcached.so && \
    ln -sf /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2.0.0 /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2.0 && \
    ln -sf /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2.0.0 /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2 && \
    ln -sf /usr/lib/x86_64-linux-gnu/libmemcachedutil.so.2.0.0 /usr/lib/x86_64-linux-gnu/libmemcachedutil.so && \
    ln -sf /usr/lib/x86_64-linux-gnu/libsybdb.so.5.0.0 /usr/lib/x86_64-linux-gnu/libsybdb.so.5.0 && \
    ln -sf /usr/lib/x86_64-linux-gnu/libsybdb.so.5.0.0 /usr/lib/x86_64-linux-gnu/libsybdb.so.5 && \
    ln -sf /usr/lib/x86_64-linux-gnu/libsybdb.so.5.0.0 /usr/lib/x86_64-linux-gnu/libsybdb.so

# Copy extensions
COPY --from=builder \
    /opt/bitnami/php/lib/php/extensions/*.so \
    /opt/bitnami/php/lib/php/extensions/

# Update INI with extensions.
RUN echo " \
\\n\
zend_extension = /opt/bitnami/php/lib/php/extensions/xdebug.so\\n\
extension      = igbinary.so\\n\
extension      = memcached.so\\n\
extension      = msgpack.so\\n\
extension      = pdo_dblib.so\\n\
extension      = redis.so\\n\
extension      = timezonedb.so\\n\
\\n\
xdebug.remote_enable       = 1\\n\
xdebug.remote_port         = 9001\\n\
xdebug.remote_host         = 172.21.0.4\\n\
xdebug.remote_connect_back = 1\\n\
xdebug.scream              = 0\\n\
xdebug.cli_color           = 1\\n\
xdebug.show_local_vars     = 1\\n\
xdebug.remote_autostart    = 1\\n\
\\n\
xdebug.var_display_max_depth    = 5\\n\
xdebug.var_display_max_children = 256\\n\
xdebug.var_display_max_data     = 1024\\n\
xdebug.max_nesting_level        = 400\\n\
\\n" >> /opt/bitnami/php/etc/php.ini

```
 Happy to discuss this further here if necessary. It comes under the heading of "works for us", YMMV, IANAL, OYOHBI, Caveat Emptor, etc.

**Comment by rquadling** [comment]
What's missing/PITA here is the need to alter the main php.ini file. I've asked for the ability to scan a directory for additional ini files, but have been told that this is not scheduled.

But ... (oh joy) ... just read http://php.net/manual/en/configuration.file.php#configuration.file.scan.

So, hopefully this can be done a LOT easier!!!

**Comment by tompizmor** [comment]
Scanning a directory for additional .ini files is a feature that we want to add to the php-fpm container and the progress will be tracked at https://github.com/bitnami/bitnami-docker-php-fpm/issues/104.

**Comment by pekechis** [comment]
After installing php-xdebug  I've found xdebug.so under the /usr/lib/php/20151012/ 
so I thought that adding he following lines to /opt/bitnami/php/etc/pnp.ini would be enough:

```
[Xdebug]
zend_extension = xdebug.so
xdebug.remote_enable = true
xdebug.remote_host= 192.168.X.X
xdebug.remote_port = 9000
xdebug.remote_autostart=1
xdebug.remote_connect_back=0
xdebug.idekey = docker
```
But i'm getting undefined symbol: php_log_err. Any clue?. It would be great to get xdebug working as a default env var.

**Comment by tompizmor** [comment]
Hi @pekechis,

If the xdebug.so file is not in the default php extension directory (`/opt/bitnami/php/lib/php/extensions/`) you may need to specify the absolute path.

Can you try the following config?

```
[Xdebug]
zend_extension = /usr/lib/php/20151012/xdebug.so
xdebug.remote_enable = true
xdebug.remote_host= 192.168.X.X
xdebug.remote_port = 9000
xdebug.remote_autostart=1
xdebug.remote_connect_back=0
xdebug.idekey = docker
```

**Comment by pekechis** [comment]
I had already tried this but i moved xdebug.so to the folder you mentioned. No matter if I use /usr/lib/php/20151012/xdebug.so or the moved xedbug.so under /opt/bitnami/lib/php/extensions, I'm always getting "undefined symbol: php_log_err". I'm guessing that perhaps I'm missing some libray.

Thanks

**Comment by pekechis** [comment]
Well, solved

While php-dev is not installed you can't "pecl install xdebug". Once it's installed the docker-compose is no longer showing the xdebug.so  "undefined symbol: php_log_err".

However now I'm getting opcache.so: undefined symbol: pcre_exec
XDDDDDDD. I'll let you know

**Comment by tompizmor** [comment]
@pekechis how did you installed xdebug? I think you need to compile it from source. Did you do that?

**Comment by pekechis** [comment]
Didn't have to...
pecl install xdebug
apt-get install php-dev

Now I can't debug from the host machine without any problem. The container is only showing the problem with the opcache.so. 

Thanks @tompizmor

**Comment by pekechis** [comment]
I did. I'm not having any problem with Xdebug. Problems are with opcache.so

**Comment by tompizmor** [comment]
Ok ok! I just wanted to know because I have compiled it and I could load the xdebug extension without issues.
