### ISSUE TITLE
Changes in code not being reflected

### ISSUE THREAD

**Issue by SubodhDahal** [bitnami/bitnami-docker-laravel#84]
**Description**

I have been using this docker image for Laravel development and most of the time the changes I make to the code are not immediately reflected to the expected output. Sometimes the changes take place after a few refreshes in the browser and sometimes not at all so I have to stop the containers and rerun them. 

**Steps to reproduce the issue:**

1. Add the following code in `routes/web.php`:
```
<?php
Route::get('/', function () {
    echo "First Hello";
});
```
Check the output in browser to be sure the text **First Hello**  is displayed
2. Update the above code to:
```
<?php
Route::get('/', function () {
    echo "Second Hello";
});
```

**Describe the results you received:**

Text **First Hello** in the browser.

**Describe the results you expected:**

Text **Second Hello** in the browser.

**Additional information you deem important (e.g. issue happens only occasionally):**

I'm using `docker-compose` to spin-up the containers. I used the image on an already existing Laravel application and a completely new one as specified in https://github.com/bitnami/bitnami-docker-laravel#local-workspace . Both yield the same results.

**Version**

- Output of `docker version`:

```
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:10:09 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:08:36 2018
  OS/Arch:	linux/amd64
  Experimental:	false

```

- Output of `docker info`:

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-37-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.499GiB
Name: sub0dh-ThinkPad-T430
ID: ZECI:EIYW:GM33:DQWZ:AIZ4:IZXW:VUHE:TGY2:SKCD:N4ON:LIAH:HUD4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.19.0, build 9e633ef
docker-py version: 2.7.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
I'm running Ubuntu 17.10 64-bit OS.

**Comment by javsalgar** [comment]
I was able to reproduce it. It is due to the application caching. In order to clear the cache, execute this command inside the container:

```
php artisan cache:clear
```

After that, the new page appeared immediately

**Comment by SubodhDahal** [comment]
Thanks @javsalgar. That worked, but it's frustrating to have to run the command frequently. Is it possible to disable the cache permanently for development environment?

**Comment by javsalgar** [comment]
It looks to me that it is not possible, according to this link: https://laracasts.com/discuss/channels/laravel/how-to-disable-cache-in-laravel-52

I would advise you to directly ask them and see what they say :D

**Comment by tderleth** [comment]
@SubodhDahal I figured out you need to open write access for docker container on our storage folder. Just try to chmod from your storage folder to sth like 777 (recursively) and it should work.

**Comment by marcosbc** [comment]
Hi @tderleth, I'm unsure why that fixes the caching issue, since the files are still there, but I'm glad you were able to solve it on your side.

**Comment by shiasyn** [comment]
> It looks to me that it is not possible, according to this link: https://laracasts.com/discuss/channels/laravel/how-to-disable-cache-in-laravel-52
> 
> I would advise you to directly ask them and see what they say :D

[Here](https://github.com/laravel/framework/issues/2501) you can find approach for disabling caching for the specific environment by setting ```CACHE_DRIVER=array``` in .env file

Sadly I still experiencing this issue :(

I did 
```chmod -R storage```
on my host machine first and after that inside the docker container

**Comment by Bibendus83** [comment]
For me the artisan command to clear the cache didn't work.
I had to disable opcache in my php.ini and now page modifications are refreshed instantly.

Here is what I did:

- Install nano (it's not available by default on this image)
```
sudo apt-get update 
sudo apt-get install nano
````

- Change opcache.enable=0 to opcache.enable=1 in your php.ini

```
sudo nano /opt/bitnami/php/etc/php.ini
```

- Restart your docker container (I have disk persistence so my changes are kept)

**Comment by marcosbc** [comment]
Thanks for sharing @Bibendus83! That makes sense, as Opcache is a feature enabled by default. We could discuss whether it makes sense to disable it by default in Bitnami development images (e.g. Laravel). I've created an internal task for that purpose.

**Comment by Bibendus83** [comment]
It would be nice to have an ENV setting to choose development or production environment.

**Comment by E-Bismuth** [comment]
other way : first line of server.php : opcache_reset();

**Comment by javsalgar** [comment]
Thanks for the input. As soon as we have more news on this, we will update the ticket

**Comment by joetito1** [comment]
@javsalgar Any update on this?

**Comment by javsalgar** [comment]
Hi,

I am afraid it is still in our backlog. I forwarded it to the engineering team for prioritization.

**Comment by rafariossaa** [comment]
Hi,
  We have made a new release where opcache is disabled.
  Could you give it a try ?.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-laravel#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
