### ISSUE TITLE
Unnecessary update

### ISSUE THREAD

**Issue by balintsera** [bitnami/bitnami-docker-laravel#90]
First of all, thank you for this image! 

https://github.com/bitnami/bitnami-docker-laravel/blob/20b52f8252e827a1c2fb8bc4d12ebb0476593b3e/5/rootfs/app-entrypoint.sh#L20

This function checks whether the package.json file is edited since the last init session but Composer has a lock file so its more convenient just to run a `composer install`. 

This will

1. look for a composer.lock file. This file has every dependency locked to a specific version so it installs/reverts the contents of the vendor directory to these versions

2. if the lock file is missing, `composer install` installs the higher versions of all the packages according to the version controls that can be found in composer.json.

So there is no need to run composer update unless the user deliberately want to update all of the packages.

It can result in unintended updates in every environment (if the lock file is commited).

So I suggest to run `composer install` instead of update. If the developer wants to update the packages, she/he can do it by running the update command in the container. 

Am I missed something important? Should I submit a merge request with this?

**Comment by rafariossaa** [comment]
Hi @balintsera ,
  We are currently studying your proposal. 
  We will have an answer in the following days.

**Comment by balintsera** [comment]
Thank you very much, I will try to find some time on the weekend to help you with a pull request

**Comment by rafariossaa** [comment]
Hi @balintsera ,

  We discussed about your proposal, and we agree that it is better the way you suggested.
  Please feel free to send the PR.

**Comment by florianrusch** [comment]
@rafariossaa is there a plan to accept the PR in the near future?

**Comment by tompizmor** [comment]
Hi @florianrusch,

We are working on refactoring the laravel container. The functionality will remain the same but we will reorganize files and logic. Once that refactor is complete, I will test the PR and apply the changes.

**Comment by tompizmor** [comment]
Hi @balintsera @florianrusch,

We have finished the refactoring of the laravel container including the changes proposed in this PR. Please take a look at the current container and close this PR if everything is fine.

**Comment by florianrusch** [comment]
@tompizmor thanks for your work :-)
can be closed I think.

**Comment by balintsera** [comment]
@tompizmor thank you for this update. I checked the entrypoint script but I still think that it's suboptimal.
`Composer update` command updates _every package and their dependencies_ that it finds in the `composer.json` file to the latest (enabled by the version constrain string). This could result unintended changes in the container and I think that with continuous integration and delivery, it is very important to keep every environments identical.  
Using `composer install` would be more appropriate here, because it installs the same packages in every environments using the lock file.

**Comment by tompizmor** [comment]
You are right! I missed that change when applying the changes from the PR.
I will release new versions of the images and update this thread

**Comment by tompizmor** [comment]
Docker images updated!

**Comment by balintsera** [comment]
I can see that, thank you :)

... and in a possible next version it would be very helpful to have a separate production and dev version, because composer has some useful switches for production:
`composer install --no-dev --optimize-autoloader`
