### ISSUE TITLE
how to install php ext dependencies?

### ISSUE THREAD

**Issue by dev-kang** [bitnami/bitnami-docker-laravel#96]
My project  required the ext-mongodb ^1.4.0.  How can i install it ?

	myapp_1_d223d9ceae09 | Loading composer repositories with package information
	myapp_1_d223d9ceae09 | Installing dependencies (including require-dev) from lock file
	myapp_1_d223d9ceae09 | Your requirements could not be resolved to an installable set of packages.
	myapp_1_d223d9ceae09 | 
	myapp_1_d223d9ceae09 |   Problem 1
	myapp_1_d223d9ceae09 |     - mongodb/mongodb 1.3.2 requires ext-mongodb ^1.4.0 -> the requested PHP extension mongodb is missing from your system.
	myapp_1_d223d9ceae09 |     - mongodb/mongodb 1.3.2 requires ext-mongodb ^1.4.0 -> the requested PHP extension mongodb is missing from your system.
	myapp_1_d223d9ceae09 |     - Installation request for mongodb/mongodb 1.3.2 -> satisfiable by mongodb/mongodb[1.3.2].
	myapp_1_d223d9ceae09 | 
	myapp_1_d223d9ceae09 |   To enable extensions, verify that they are enabled in your .ini files:
	myapp_1_d223d9ceae09 |     - /opt/bitnami/php/lib/php.ini
	myapp_1_d223d9ceae09 |   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by andresbono** [comment]
Hi @dev-kang, can you try to modify the _Dockerfile_ to install `mongodb` _PHP_ extension? You should add the following lines right before the `USER bitnami` line:

```Dockerfile
...

RUN install_packages build-essential autoconf
RUN pecl install mongodb
RUN echo "extension=mongodb.so" >> /opt/bitnami/php/lib/php.ini

...
```

Then, if you build the container image again, you will be able to execute the command to add `mongodb` _PHP_ extension to your _Laravel_ application:

```
composer require mongodb/mongodb
```

Let us know if it works for you.
