### ISSUE TITLE
Error 500 on docker-compose up

### ISSUE THREAD

**Issue by pekechis** [bitnami/bitnami-docker-laravel#99]
Maybe is a stupid question. Sorry in advance, I'm a docker-compose starter....

I'm using the following docker-compose:

`version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=xxxxxxx
      - MARIADB_DATABASE=xxxxxx
      - MARIADB_PASSWORD=xxxxxx

  myapp:
    tty: true
    image: 'bitnami/laravel:latest'
    labels:
      kompose.service.type: nodeport
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=xxxxxx
      - DB_DATABASE=xxxxxx
      - DB_PASSWORD=xxxx
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ../myapp:/app
`

At the myapp folder I've my bitckbucket repo without the vendor folder (added to .gitignore) and once I launch the service with docker-compose up:

- The vendor folder is created
- All dependencies from the composer.json are downloaded without any problem (or at least It seems to)
- All the migrations are correctly executed.
- The app is served at http://127.0.0.1:3000

But no matter what url I try I'm getting a 500 error and I don't know where to find more info inside the bitnami container.

Thanks in advance.

**Comment by andresbono** [comment]
Hi @pekechis,

Do the docker-compose logs show any clues about the error? You can execute the following command:

```
docker-compose logs myapp
```

Did you try to run your _Laravel_ application in a different environment before?

**Comment by pekechis** [comment]
Hi @andresbono 

Thanks for your answer. Finally I've found the problem (It's my problem ;) )

When docker-compose up is run for the first time, as the container is built correctly, the code from the repo is mounted at the right place (/app folder), all the dependencies at composer.json are installed and all the migrations are  run ( due to the ENV vars in the docker-compose.yaml)

But, as my **_.gitignore_** includes **_.env_** and **_./storage/*.keys_** Laravel doesn't serve the App and the response is always an error 500.

I only needed to move .env.example to .env and  execute php artisan key:generate. No problem now.

Some questions for you @andresbono, shouldn't be great to add this kind of info to the Readme.md?  Can I propose a pull request for this kind of installation (from an external repo with no .env and keys?

I believe that placing these files under CVS is an anti-pattern and sometimes is very useful to remind developers these issues through the installation instructions.

**Comment by andresbono** [comment]
Hi @pekechis, great to hear that you found the issue and you could solve it! 🎉

> Some questions for you @andresbono, shouldn't be great to add this kind of info to the Readme.md? Can I propose a pull request for this kind of installation (from an external repo with no .env and keys?

Of course! Feel free to send the PR and we'll review and merge it.

I'd recommend to add your use case as an example under https://github.com/bitnami/bitnami-docker-laravel#getting-started.

If you want to explain the key generation, maybe it fits better under https://github.com/bitnami/bitnami-docker-laravel#executing-commands.
